### ISSUE TITLE
Binding not installing - 2.5.0.jar

### ISSUE THREAD

**Issue by McNose** [FluBBaOfWard/openhab2-addons#1]
Hi,

I added the 2.5.0.jar file in my openhab2/addon folder an rebootet the paspberry pi.
The binding gets not installed.
I tried the same with the older 2.4.0.jar file and it works.

There might be a bug in 2.5.0. Or am i doing something wrong?

Beside this, I didnt had the time to test the 2.4.0 binding jet. I have got a LG hombot VRH950mspcm. Do you know if it is supported as well?

Thank you.

Grettings

**Comment by FluBBaOfWard** [comment]
I not sure how the plugins and their dependencies should work in OpenHab 2.5 yet so I don’t know what can be wrong, I hope someone can do the code review and maybe point me in the right direction.
Regarding your HomeBot, have you installed the custom firmware and added a USB-WiFi stick? I will not tell you to do that because of the risk involved in modifying your tech.

/Fredrik
